/**:
  ros__parameters:
    plugins_path: $(find-pkg-share autoware_tensorrt_plugins)/plugins/libautoware_tensorrt_plugins.so
    onnx_model_path: $(env HOME)/autoware_data/diffusion_planner/2026_05_13/diffusion_planner.onnx
    args_path: $(env HOME)/autoware_data/diffusion_planner/2026_05_13/diffusion_planner.param.json
    planning_frequency_hz: 10.0
    ignore_neighbors: false
    ignore_unknown_neighbors: true
    traffic_light_group_msg_timeout_seconds: 0.2
    batch_size: 1
    temperature: [0.0]
    # batch_size: 16
    # temperature: [1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5,1.5]
    velocity_smoothing_window: 8
    stopping_threshold: 0.3
    turn_indicator_keep_offset: -1.25
    turn_indicator_hold_duration: 1.0
    shift_x: false
    delay_step: 0
    line_string_max_step_m: 5.0
    use_time_interpolation: false

    # ここをPALTAを参照して加える
    wheel_radius: 0.13 # The radius of the wheel, primarily used for dead reckoning.
    wheel_width: 0.07 # The lateral width of a wheel tire, primarily used for dead reckoning.
    wheel_base: 0.30 # between front wheel center and rear wheel center
    wheel_tread: 0.33 # between left wheel center and right wheel center
    front_overhang: 0.256 # between front wheel center and vehicle front
    rear_overhang: 0.317 # between rear wheel center and vehicle rear
    left_overhang: 0.105 # between left wheel center and vehicle left
    right_overhang: 0.105 # between right wheel center and vehicle right
    vehicle_height: 0.922
    max_steer_angle: 1.57 # [rad]

    planning_factor:
      enable_stop: true
      enable_slowdown: false
      stop_keep_duration_threshold: 1.0  # [s]
      stop_velocity_threshold: 0.1       # [m/s]
      slowdown_accel_threshold: -0.3     # [m/s^2]
    debug_params:
      publish_debug_route: true
      publish_debug_map: false
      publish_debug_linestrings: true
